config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/signup', to: 'users#new'
  post '/signin', to: 'users#create'
  get '/', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/home', to: 'sessions#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fridge.rb
class Fridge < ApplicationRecord
    
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  user = User.find_by(login: params[:session][:login].downcase)
	  if user && user.authenticate(params[:session][:password])
	    session[:user_id] = user.id
	    flash[:notice] = "Logged in successfully."
	    redirect_to '/home'
	  else
	    flash.now[:alert] = "There was something wrong with your login details."
	    render 'login'
	  end
	end

	def destroy
	  session[:user_id] = nil
	  flash[:notice] = "You have been logged out."
	  redirect_to root_path
	end

	def home
		require File.join(Rails.root, 'parseJson.rb');

		$recipes = read_recipes
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
	   @user = User.new
	 end

	 def create
	   @user = User.new(user_params)
	   if @user.save
	     flash[:notice] = "User created."
	     redirect_to '/'
	   else
	     render 'signup'
	   end
	 end

	private

	 def user_params
	   params.require(:user).permit(:firstname, :lastname, :login, :password)

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# helper_method :current_user, :logged_in?
	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
	  !!current_user
	end

	def require_user
	  if !logged_in?
	    flash[:alert] = "You must be logged in to perform that action."
	    redirect_to login_path
	  end
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>On mange quoi ce soir ?</h1>

<% @users.each do |user| %>
	<p><%= user.id %></p>
	<p><%= user.firstname %></p>
	<p><%= user.lastname %></p>
	<p><%= user.login %></p>
	<p><%= user.password %></p>
<% end %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true, url: signin_path) do |f| %>

<div class="form-group">
  <%= f.label :firstname %><br/>
  <%= f.text_field :firstname, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :lastname %><br/>
  <%= f.text_field :lastname, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :login %><br/>
  <%= f.text_field :login, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.submit %>
</div>

<% end %>

<p>Déjà membre ? <a href="/">Connectez-vous !</a></p>